version: '3.9'
services:
  mc-vanilla:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - "/var/minecraft/server/data:/app/minecraft"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Singapore"
    restart: always
