version: "3.9"
services:
  super-simple-mc-server:
    build: ..
    ports:
      - "25565:25565"
    volumes:
      - "../data:/app/minecraft/server-data"
      - "../src:/app/minecraft/bin"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Singapore"
      START_CMD: "java -Xmx4096M -Xms1024M -jar ./minecraft_server.1.20.4.jar nogui"
      BACKUP_DURATION: 15
      RCON_PASSWORD: 'admin'
      ENABLE_BACKUP: 'TRUE'
    restart: always
