version: "3.9"
services:
  super-simple-mc-server:
    build: ..
    ports:
      - "25565:25565"
    volumes:
      - "./data:/app/minecraft/server-data"
      - "./src:/app/minecraft"
    environment:
      EULA: "TRUE"
      TZ: "Asia/Singapore"
    restart: always
